# Generated by Django 3.0.6 on 2020-06-14 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='username',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
