# Generated by Django 3.0.7 on 2020-06-15 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject_assigned',
            name='remarks',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
