# Generated by Django 3.0.7 on 2020-06-15 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0003_auto_20200615_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='semester',
            field=models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8)]),
        ),
    ]
